#!/bin/busybox sh
. /etc/initram.conf

[ "x$usetpm" = "xyes" -a -e /sbin/tpm_mount_root ] && /sbin/tpm_mount_root

if [ "x$localunlock" = "xyes" -a ! -e /dev/mapper/ckey ]; then
	/bin/mount_crypt &
	lmrpid=$!
fi

#Try to wait for root to log in
sleep 10;

while [ ! -e /dev/mapper/ckey ]; do
	sleep 1;
done;

[ "x$localunlock" = "xyes" -a "x$lmrpid" != "x" ] && (
	kill $lmrpid && sleep 1
	kill -9 $lmrpid
) &

while [ -e /root_session ]; do
	sleep 60;
done;

[ -e /dev/mapper/ckey ] || exit 1

for d in $cryptounlock; do /sbin/cryptsetup open "/dev/$d" "crypto$d" --allow-discards -d /dev/mapper/ckey; done
/sbin/cryptsetup close /dev/mapper/ckey

if [ "x$roottype" = "xbtrfs" ]; then
	#Scan for devices
	/sbin/btrfs device scan $(for d in $rootpath; do echo "/dev/mapper/crypto$d"; done)
	for d in $rootpath; do /sbin/btrfs device ready "/dev/mapper/crypto$d" && break; done
fi

# Mount the root filesystem.
for d in $rootpath; do  mount -t "$roottype" "/dev/mapper/crypto$d" /mnt/root "-oro$rootopts" || exit 1 && break; done;
